TARGET = test

INCLUDEPATH = 3rdparty/lib1/include \
    3rdparty/lib2/include

SOURCES = Agent.cpp Message.cpp MessageEvent.cpp MotionAgent.cpp ManagerAgent.cpp thread.cpp  main.cpp

#LIBPATH = 3rdparty/lib1/lib \
    #3rdparty/lib2/lib

#LIBS = lib1 \
    #lib2

DEFINES = NDEBUG

include build.mk
